export const SET_SINGRT: string = 'SET_SINGER'
export const SET_PLAYING: string = 'SET_PLAYING'
export const SET_FULLSCREEN: string = 'SET_FULLSCREEN'
export const SET_PLAY_LIST: string = 'SET_PLAYLIST'
export const SET_SQUENCE_LIST: string = 'SET_SQUENCELIST'
export const SET_PLAY_MODE: string = 'SET_PLAY_MODE'
export const SET_CURRENT_INDEX: string = 'SET_CURRENT_INDEX'